In [ ]:
# convert List to tuple
month = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']  
converting_list = tuple(month)  
print(converting_list)  
print(type(converting_list))  

In [1]:
import numpy  
#method 1  
array_1 = numpy.array([])  
print(array_1)  
#method 2  
array_2 = numpy.empty(shape=(3,3))  
print(array_2)  

[]
[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 4.92e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


In [2]:
import array  
a = [4, 6, 8, 3, 1, 7]  
print(a[-3])  
print(a[-5])  
print(a[-1])  

3
6
7


In [ ]:
Print( sum(range(1,102)) )  

In [ ]:
# calculate the mean of a number in the list
n = int(input("Number of Elements to take average of: "))  
l=[]  
for i in range(1,n+1):  
    element = int(input("Enter the element: "))  
    l.append(element)  
average = sum(l)/n  
print("Average of the elements in list",round(average,2))  

In [ ]:
# program to reverse a number 
n = int(input("Enter number: "))  
  
reverse = 0  
  
while(n>0):  
    digit = n%10  
    reverse = reverse*10+digit  
    n=n//10  
print("The reverse of the number:",reverse)  

In [ ]:
list_comp = [i for i in range(4)]  
print(list_comp)  

In [ ]:
dictt = {i : i+2 for i in range(10)}  
print(dictt)  

In [ ]:
# Python program to show how global variables and local variables are different  
var = 56  
# Creating a function  
def addition():  
    var1 = 7  
    c = var + var1  
    print("In local scope: ", var1)  
    print("Adding a global scope and a local scope variable: ", c)  
addition()  
print("In global scope: ", var)

In [ ]:
# Python program to show the difference between a list and an array  
  
# Importing array module  
import array as arr  
  
# Creating an array and a list  
array_1 = arr.array("i", [3, 6, 2, 7, 9, 5])  
list_1 = [4, 'Interview', 7.20]  
  
print(array_1)  
print(list_1)  
  
# Trying to create an array with multiple data types  
try:  
    array_2 = arr.array("i", [3, 7, 3, "Interview"])  
except Exception as e:  
    print(e)  

In [ ]:
In Python, __init__ is a function or function Object() { [native code] }.
When a new object/instance of a class is created, this function is automatically called to reserve memory. 
The __init__ method is available in all classes.

In [ ]:
# Python program to explain __init__  
  
class Student:  
    def __init__(self, st_name, st_class, st_marks):  
        self.st_name = st_name  
        self.st_class = st_class  
        self.st_marks = 67  
S1 = Student("Tanu", 10, 67)  
print(S1.st_name)  
print(S1.st_class) 

- A lambda function is a type of nameless function. This method can take as many parameters as you want but a single statement.

In [3]:
# Python program to show how to use lambda functions  
  
# Creating a lambda function for addition  
sum_ = lambda x, y, z : x + y + z  
print("Sum using lambda function is: ", sum_(4, 6, 8))  

Sum using lambda function is:  18


In [4]:
# Python program to show to randomise elements of a list  
  
# Importing the random module  
import random  
list_ = ["Python", "Interview", "Questions", "Randomise", "List"]  
print("Original list: ", list_)  
random.shuffle(list_)  
print("After randomising the list: ", list_)  

Original list:  ['Python', 'Interview', 'Questions', 'Randomise', 'List']
After randomising the list:  ['Randomise', 'List', 'Interview', 'Questions', 'Python']


In [5]:
# Python program to show how to convert a string to lower case  
  
string = 'PYTHONISAREPTILE'  
print(string.lower()) 

pythonisareptile


In [ ]:
# Python program to show how to write a docstring  
  
""" 
This is a docstring. 
We write docstrings to explain a program. 
This program will multiply two numbers and then display the output. 
"""  
a = 39  
b = 45  
c = a * b  
print("Result of multiplication: ", c)  

In [8]:
# Python program to show how to add elements to an array  

array = arr.array('d', [1 , 2 ,3] )  
array.append(8) # appending will add an element to the end of the array  
print(array)  
array.extend([4,6,9]) # extending will add elements by looping through the given iterable  
print(array)  
array.insert(2, 9) # inserting will add the element at the specified index  
print(array)  

NameError: name 'arr' is not defined